networks:
  common:
    external: true
    name: common

services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    labels:
      logging: promtail
      prometheus-job: true
    container_name: md-converter-service
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./logs:/app/logs  # Для логов, если понадобятся
    networks:
      - common