env: "local"
app:
  token_ttl: 300h
http_server:
  port: 8080
  timeout: 4s
tg_client:
  token: 7550143505:AAFsjHU8x90K8KbTAIPhpMZzF0HUGIGEX3g
#  token: 7071475834:AAE3-DmHqbFa1nkXRlhCCry4Dm2EvQJq1Kk
  chat_id: -1002549996890
tz_bot_service:
  addr: localhost:8081