env: "local"
app:
  token_ttl: 300h
http_server:
  port: 8080
  timeout: 4s
postgres:
  host: 94.241.142.172
  #  port: "8030"
  port: "9030"
  database_name: logs
  username: aAKSHDVasvd
  password: dbsaLSAGVDvadaj
  max_connections: 10
tg_client:
  token: 7071475834:AAE3-DmHqbFa1nkXRlhCCry4Dm2EvQJq1Kk
  #  token: 7550143505:AAFsjHU8x90K8KbTAIPhpMZzF0HUGIGEX3g
  chat_id: -1002870769486
tz_bot_service:
  addr: localhost:8081
redis:
#  address: 94.241.142.172:6379
  address: 94.241.142.172:9380
  password: r8VwP2mQe7Jx1Tz9Hb4Kc6Nf3Lg5Yd8
user_service:
#  address: localhost:8001
   address: localhost:9087
chat_bot_service:
  address: localhost:9082