env: "local"
app:
  token_ttl: 300h
http_server:
  port: 8001
  timeout: 4s
tg_client:
  token: 7071475834:AAE3-DmHqbFa1nkXRlhCCry4Dm2EvQJq1Kk
  chat_id: -1002870769486
tz_bot_service:
  addr: "localhost:9090"