networks:
  common:
    external: true
    name: common

services:
  app:
    container_name: report-generator-service
    build: .
    labels:
      logging: promtail
      prometheus-job: true
    restart: unless-stopped
    networks:
      - common
