env: "local"
app:
  token_ttl: 300h
http_server:
  port: 8001
  timeout: 600s
grpc_server:
  port: localhost:8081
llm_client:
 url: http://localhost:8000/analyze
 model: "qwen3-235b-a22b-fp8/latest"
word_parser_client:
  url: http://localhost:8082
markdown_service_client:
  url: http://localhost:8089
s3minio:
  host: localhost
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
tg_client:
  token: 7071475834:AAE3-DmHqbFa1nkXRlhCCry4Dm2EvQJq1Kk
#  token: 7550143505:AAFsjHU8x90K8KbTAIPhpMZzF0HUGIGEX3g
  chat_id: -1002870769486