env: "local"
app:
  token_ttl: 300h
postgres:
  host: localhost
  port: 8002
  database_name: technical_specs
  username: aAKSHDVasvd
  password: dbsaLSAGVDvadaj
  max_connections: 1
grpc_server:
  port: localhost:8081
promt_builder:
  url: http://localhost:8010/v1/prompt-builder/build
llm_client:
 url: http://localhost:8020/v1/structured/run
 model: "qwen3-235b-a22b-fp8/latest"
word_parser_client:
  url: http://localhost:8082
word_parser_client2:
  host: localhost
  port: 8060
doc_to_docx_converter_client:
  host: localhost
  port: 8070
report_generator_client:
  host: localhost
  port: 8050
markdown_service_client:
  url: http://localhost:8089
s3minio:
  host: localhost
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
tg_client:
  token: 7550143505:AAFsjHU8x90K8KbTAIPhpMZzF0HUGIGEX3g
  chat_id: -1002549996890
  use_webhooks: false
  webhook_host: ""
  webhook_port: 8443
  webhook_path: "/webhook"