env: "local"
app:
  token_ttl: 300h
postgres:
  host: 94.241.142.172
  port: 8002
  database_name: technical_specs
  username: aAKSHDVasvd
  password: dbsaLSAGVDvadaj
  max_connections: 1
grpc_server:
  port: localhost:8081
promt_builder:
  url: https://promtbuilder.timuroid.ru/v1/prompt-builder/build
llm_client:
  url: https://llmrequester.timuroid.ru/v1/structured/run
  model: "qwen3-235b-a22b-fp8/latest"
word_parser_client:
  url: http://94.241.142.172:8082
word_parser_client2:
  host: localhost
  port: 8060
markdown_service_client:
  url: http://localhost:8089
s3minio:
  host: 94.241.142.172
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
tg_client:
  token: 7071475834:AAE3-DmHqbFa1nkXRlhCCry4Dm2EvQJq1Kk
  chat_id: -1002870769486