env: "local"
app:
  token_ttl: 300h
http_server:
  port: 8001
  timeout: 4s
grpc_server:
  port: localhost:9090
llm_client:
  url: http://94.228.122.106:9000/analyze
word_parser_client:
  url: http://localhost:8000
s3minio:
  host: localhost
  port: 9000
  accessKey: minioadmin
  secretKey: minioadmin
tg_client:
  token: 7071475834:AAE3-DmHqbFa1nkXRlhCCry4Dm2EvQJq1Kk
  chat_id: -1002870769486