env: "local"

telegram:
  bot_token: "YOUR_TELEGRAM_BOT_TOKEN"

postgres:
  host: "localhost"
  port: "5432"
  database_name: "telegram_bot"
  username: "postgres"
  password: "postgres"
  max_connections: 10

user_service:
  address: "localhost:8001"
  timeout: 10s

chat_service:
  address: "localhost:50053"
  timeout: 10s