env: "local"

telegram:
  bot_token: "7584175600:AAGT2d_ypZDzInzYJ_xf8SHhKmT-Pit83UM"

postgres:
#  host: "94.241.142.172"
  host: "localhost"
  port: "9078"
  database_name: "telegram_bot"
  username: "QvXiuBQFQHOy"
  password: "vkIeydiDtJWqUpQVOmHm"
  max_connections: 10

user_service:
#  address: "localhost:8001"
  address: "localhost:9087"
  timeout: 10s

chat_service:
  address: "localhost:9082"
  timeout: 60s