env: "local"
grpc_server:
  port: localhost:9082
postgres:
  host: localhost
  port: 9081
  database_name: chat_bot
  username: QvXiuBQFQHOy
  password: vkIeydiDtJWqUpQVOmHm
  max_connections: 10
llm_client:
  url: http://localhost:7000