env: "local"
grpc_server:
  port: localhost:9082
postgres:
  host: 94.241.142.172
  port: 9081
  database_name: chat_bot
  username: QvXiuBQFQHOy
  password: vkIeydiDtJWqUpQVOmHm
  max_connections: 10
llm_client:
  url: http://94.228.122.106:8000