networks:
  common:
    external: true
    name: common

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docx-converter-service
    labels:
      logging: promtail
      prometheus-job: true
    volumes:
      # Монтируем логи для доступа с хоста
      - ./logs:/app/logs
      # Для разработки - монтируем код (раскомментируйте при необходимости)
      # - ./app:/app/app
      # - ./main.py:/app/main.py
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - common
