networks:
  common:
    external: true
    name: common

services:
  maddy:
    image: foxcpp/maddy:latest
    container_name: maddy
    restart: unless-stopped
    hostname: mail.intbis.ru
    networks:
      - common
    labels:
      logging: promtail
      prometheus-job: true
    environment:
      - TZ=Europe/Amsterdam
      - MADDY_HOSTNAME=mail.intbis.ru
      - MADDY_DOMAIN=intbis.ru
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - maddy_data:/data                      # ИМЕНОВАННЫЙ VOLUME ← важно
      - /etc/letsencrypt/live/intbis.ru/fullchain.pem:/data/tls/fullchain.pem:ro
      - /etc/letsencrypt/live/intbis.ru/privkey.pem:/data/tls/privkey.pem:ro

  mailer:
    build: ./mailer
    container_name: mailer-service
    restart: unless-stopped
    networks:
      - common
    labels:
      logging: promtail
      prometheus-job: true
    environment:
      - SMTP_HOST=maddy
      - SMTP_PORT=587
      - SMTP_USER=noreply@intbis.ru
      - SMTP_PASS=ЗАДАЙТЕ_ПОСЛЕ_СОЗДАНИЯ_ПОЛЬЗОВАТЕЛЯ
      - SMTP_FROM="ИнтБис <noreply@intbis.ru>"
    depends_on:
      - maddy
#    ports:
#      - "8085:8080"   # HTTP API вашего сервиса для отправки
volumes:
  maddy_data: