networks:
  common:
    external: true
    name: common

services:
  maddy:
    image: foxcpp/maddy:latest
    container_name: maddy
    restart: unless-stopped
    hostname: mail.intbis.ru
    networks:
      common:
        aliases:
          - mail.intbis.ru        # <— алиас в сети common
    labels:
      logging: promtail
      prometheus-job: true
    environment:
      - TZ=Europe/Amsterdam
      - MADDY_HOSTNAME=mail.intbis.ru
      - MADDY_DOMAIN=intbis.ru
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - maddy_data:/data
      # оставляем ТОЛЬКО сертификат для mail.intbis.ru
      - /etc/letsencrypt/live/mail.intbis.ru/fullchain.pem:/data/tls/fullchain.pem:ro
      - /etc/letsencrypt/live/mail.intbis.ru/privkey.pem:/data/tls/privkey.pem:ro

  mailer:
    build: ./mailer
    container_name: mailer-service
    restart: unless-stopped
    networks:
      - common
    labels:
      logging: promtail
      prometheus-job: true
    environment:
      - SMTP_HOST=mail.intbis.ru   # <— теперь совпадает с CN/SAN сертификата
      - SMTP_PORT=587
      - SMTP_USER=noreply@intbis.ru
      - SMTP_PASS=123
      - SMTP_FROM_ADDR=noreply@intbis.ru
      - SMTP_FROM_NAME=ИнтБис
    depends_on:
      - maddy
#    ports:
#      - "8085:8080"   # HTTP API вашего сервиса для отправки
volumes:
  maddy_data: