networks:
  common:
    external: true
    name: common

services:
maddy:
  image: foxcpp/maddy:latest
  container_name: maddy
  restart: unless-stopped
  hostname: mail.intbis.ru
  environment:
    - TZ=Europe/Amsterdam
    - MADDY_HOSTNAME=mail.intbis.ru     # имя MX
    - MADDY_DOMAIN=intbis.ru            # основной домен
  ports:
    - "25:25"
    - "465:465"
    - "587:587"
    - "993:993"
  volumes:
    - ./maddy/data:/data
    # Сертификаты Let's Encrypt — в пути, которые ожидает образ:
    - /etc/letsencrypt/live/intbis.ru/fullchain.pem:/data/tls/fullchain.pem:ro
    - /etc/letsencrypt/live/intbis.ru/privkey.pem:/data/tls/privkey.pem:ro

  mailer:
    build: ./mailer
    container_name: mailer-service
    restart: unless-stopped
    networks:
      - common
    environment:
      - SMTP_HOST=maddy
      - SMTP_PORT=587
      - SMTP_USER=noreply@intbis.ru
      - SMTP_PASS=ЗАДАЙТЕ_ПОСЛЕ_СОЗДАНИЯ_ПОЛЬЗОВАТЕЛЯ
      - SMTP_FROM="ИнтБис <noreply@intbis.ru>"
    depends_on:
      - maddy
#    ports:
#      - "8085:8080"   # HTTP API вашего сервиса для отправки
