services:
  repair-copilot-bot-postgres:
    container_name: postgres_container_repair_copilot_bot
    image: postgres:14.8-alpine3.18
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.txt.1.txt"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "repair-copilot-bot"
      POSTGRES_USER: "repair-copilot-bot-admin"
      POSTGRES_PASSWORD: "ASDasd12862fv"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../../../migrations:/docker-entrypoint-initdb.d
      - repair-copilot-bot-postgres-data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iamil-admin -d repair-copilot-bot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.txt'
          memory: 4G
    networks:
      - repair-copilot-bot-postgres

  repair-copilot-bot-pgadmin:
    container_name: pgadmin_container_repair_copilot_bot
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "iamil50113@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "1.txt"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - repair-copilot-bot-pgadmin-data:/var/lib/pgadmin
    ports:
      - "5051:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - repair-copilot-bot-postgres

volumes:
  repair-copilot-bot-postgres-data:
  repair-copilot-bot-pgadmin-data:

networks:
  repair-copilot-bot-postgres:
    driver: bridge