services:
  telegram-bot-service-postgres:
    container_name: postgres_container_telegram_bot_service
    image: postgres:17.5-alpine3.22
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=128MB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_DB: "telegram_bot"
      POSTGRES_USER: "QvXiuBQFQHOy"
      POSTGRES_PASSWORD: "vkIeydiDtJWqUpQVOmHm"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
#      - ./user_service/migrations:/docker-entrypoint-initdb.d
      - telegram-bot-service-postgres-data:/var/lib/postgresql/data
    ports:
      - "9078:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U QvXiuBQFQHOy -d telegram_bot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - telegram-bot-service-postgres

volumes:
  telegram-bot-service-postgres-data:

networks:
  telegram-bot-service-postgres:
    driver: bridge