env: "local"
grpc_server:
  port: localhost:8001
#   port: localhost:9087
postgres:
  host: 94.241.142.172
#  port: 8085
  port: 9085
  database_name: user
  username: QvXiuBQFQHOy
  password: vkIeydiDtJWqUpQVOmHm
  max_connections: 10